### ISSUE TITLE
Twitter account to tweet when issues with label "good first issue" is created

### ISSUE THREAD

**Issue by rexdivakar** [EddieHubCommunity/gh-action-community#55]
On completion of successful PR tweet the feeds with a snapshot of the user achievements.

**Comment by eddiejaoude** [comment]
Stalebot we still want this 🤓

**Comment by Vyvy-vi** [comment]
I was planning on building a gh-action for this :)

**Comment by eddiejaoude** [comment]
Awesome! I think I have an `EddieBot` twitter account from ages ago we can use too 🎉

**Comment by jai-dewani** [comment]
Oh wow, this seems like a great idea!  
I think I can create a GitHub action that can atleast tweet out the information about the PR closed, 
Taking a SS shouldn't be that hard but I will have to look into it.
