### ISSUE TITLE
Automating invite to organisation for new members through bot

### ISSUE THREAD

**Issue by yash982000** [EddieHubCommunity/gh-action-community#57]

**Comment by eddiejaoude** [comment]
My notes

- We have access to `@actions/github`
- Which gives us access to https://octokit.github.io/rest.js/v18/
- So we might be able to do? 

```typescript
octokit.orgs.createInvitation({
  org,
});
```

**Comment by yash982000** [comment]
@eddiejaoude Thanks a lot.

**Comment by akshitagupta15june** [comment]
please invite me in organisation

**Comment by akshitagupta15june** [comment]
@eddiejaoude

**Comment by yash982000** [comment]
@akshitagupta15june I hope you have found the way as you have opened the issue.This is not the right place for it.

**Comment by eddiejaoude** [comment]
As mentioned by @yash982000 this is not the right place. @akshitagupta15june you have correctly raised an issue here https://github.com/EddieJaoudeCommunity/support/issues/401

@yash982000 I think this issue could remain open, as we are still thinking of if / how to automated the organisation invitation

**Comment by yash982000** [comment]
@eddiejaoude I had some medical emergency but after some days I will complete it, BUt if we have people interested, then sure no issues.

**Comment by eddiejaoude** [comment]
@yash982000 oh no, I hope everything is ok. No rush. We will leave it open as a reminder for us all 🤓

**Comment by yash982000** [comment]
> @yash982000 oh no, I hope everything is ok. No rush. We will leave it open as a reminder for us all

On track slowly and recovering. We will definitely make it a good and accurate working feature, even if it's a bit late

**Comment by eddiejaoude** [comment]
Don't worry, focus on getting better and recovering. We can geek out again when you have recovered 🤓

**Comment by yash982000** [comment]
@eddiejaoude Yes, thank you so much for your concern.

**Comment by Vyvy-vi** [comment]
I think this issue has been resolved by [Support#718](https://github.com/EddieHubCommunity/support/pull/718)

**Comment by eddiejaoude** [comment]
thank you @Vyvy-vi I think so too 👍
