### ISSUE TITLE
Fixing welcome action

### ISSUE THREAD

**Issue by TawfikYasser** [EddieHubCommunity/gh-action-community#63]
Hi

This issue to fix the following issues:

- [ ] [duplicate this section (without the required and default) for the footer variable](https://github.com/EddieHubCommunity/gh-action-community/blob/develop/src/welcome/action.yml#L11-L12)
- [ ] [grab the footer variable here](https://github.com/EddieHubCommunity/gh-action-community/blob/develop/src/welcome/index.js#L8)
- [ ] [remove the hardcode string here](https://github.com/EddieHubCommunity/gh-action-community/blob/develop/src/welcome/index.js#L20)

I will open a PR to fix it.

Thanks

**Comment by eddiejaoude** [comment]
Great, thank you @TawfikYasser 👍
