### ISSUE TITLE
Node Modules Inclusion

### ISSUE THREAD

**Issue by adarshaacharya** [EddieHubCommunity/gh-action-community#74]
Why node_modules folder is included in the repo && not included in .gitignore or I'm missing something ?

**Comment by eddiejaoude** [comment]
Good question @adarshaacharya 👍 - you are right, usually it is not included, but for GitHub Action they need to be included.

From the docs
> From your terminal, commit your action.yml, index.js, node_modules, package.json, package-lock.json, and README.md files. If you added a .gitignore file that lists node_modules, you'll need to remove that line to commit the node_modules directory.

https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github
