### ISSUE TITLE
GitHub Actions Enhancements

### ISSUE THREAD

**Issue by ShaikMoAbdullah** [EddieHubCommunity/gh-action-community#94]
### What would you like to share?

To add kubescape actions file to the project

**Comment by eddiejaoude** [comment]
@ShaikMoAbdullah thank you for your contribution, but this project is not deployed and has no `kubernetes` config files in it, so I will close this PR and Issue

**Comment by ShaikMoAbdullah** [comment]
Okay, Eddie. I need to look at reps. After your tweet, I'm blindly creating a kubescape actions file and getting a green square. 😁😄

**Comment by eddiejaoude** [comment]
Yes please check the config files are in the repo first in the directory `kubernetes`, you can see it from the config you are adding in your PR - otherwise it is creating more work and notifications for the maintainers
